name: gtbook
channels:
  - conda-forge
dependencies:
  - python=3.13
  - black
  - jupyter-book>=1,<2
  - python-graphviz
  - ipywidgets>=7.5
  - pandas
  - matplotlib
  - pillow # section 5.3 etc..
  - pytorch
  - torchvision
  - timm
  - nbformat
  - pip
  - pip:
      - plotly>=5.24.1,<6 # in pip for binder
      - kaleido>=0.2.1,<1 # bundled browser for png output
      - gtbook>=0.0.41
