const MAP=PAGE.data, ROWS=50,COLS=100;
const warehousePath=[...range(9,i=>[10+5*i,6]),...range(5,i=>[50,11+5*i])];
const gauss2=(p,mu,cov)=>{const d=L.sub(p,mu),det=cov[0][0]*cov[1][1]-cov[0][1]*cov[1][0];return Math.exp(-.5*(cov[1][1]*d[0]**2-2*cov[0][1]*d[0]*d[1]+cov[0][0]*d[1]**2)/det)/(2*Math.PI*Math.sqrt(det));};
const mapGrid=f=>range(ROWS,i=>range(COLS,j=>f([j+MAP.mapOrigin[0],i+MAP.mapOrigin[1]],i,j)));
const sample2=(r,mu,cov)=>{const a=Math.sqrt(cov[0][0]),b=cov[1][0]/a,c=Math.sqrt(cov[1][1]-b*b),u=r.normal(),v=r.normal();return [mu[0]+a*u,mu[1]+b*u+c*v];};
const closestBeacon=(p,max=8)=>{const rs=MAP.beacons.map(b=>L.norm(L.sub(p,b))),v=Math.min(...rs);return {index:v<=max?rs.indexOf(v):-1,range:v};};
if(PAGE.id==='S41'){
lab('mixture','Three Gaussian components','Inspect the notebook’s means (20,25), (70,40), and (50,15) with the three specified covariance matrices.',[slider('N','Samples per component',500,50,1000,50),seed()],s=>{const means=[[20,25],[70,40],[50,15]],covs=[[[25,0],[0,100]],[[400,0],[0,25]],[[40,35],[35,40]]],r=L.rng(s.seed);return {charts:[heat('Finite-grid density: sum of the three components',mapGrid(p=>L.sum(means.map((m,i)=>gauss2(p,m,covs[i])))),{caption:'100 × 50 grid · x increases right; y increases down'}),xy('Samples from each component',means.map((m,i)=>series('Component '+(i+1),range(s.N,()=>sample2(r,m,covs[i])),'scatter')),'x (m)','y (m)',{equal:true,xlim:[0,100],ylim:[0,50]})],tables:[table('Specified parameters',['Component','Mean','Covariance'],means.map((m,i)=>[i+1,m.join(', '),JSON.stringify(covs[i])]))],text:'The density image follows the notebook’s sum, whose continuous integral is 3. Divide by 3 to obtain an equal-weight mixture PMF approximation.'};},[12,14,18,20]);
lab('covariance','Shape a covariance','Stretch and correlate a Gaussian while keeping its covariance positive definite. The default is the first notebook component.',[slider('sx','σx (m)',5,1,25),slider('sy','σy (m)',10,1,25),slider('rho','Correlation ρ',0,-.95,.95,.025),seed()],s=>{const cov=[[s.sx**2,s.rho*s.sx*s.sy],[s.rho*s.sx*s.sy,s.sy**2]],r=L.rng(s.seed);return {metrics:[['Covariance determinant',cov[0][0]*cov[1][1]-cov[0][1]**2]],charts:[xy('Samples around mean (20,25)',[series('Samples',range(500,()=>sample2(r,[20,25],cov)),'scatter')],'x (m)','y (m)',{equal:true}),heat('Density on the warehouse grid',mapGrid(p=>gauss2(p,[20,25],cov)))],tables:[table('Covariance matrix',['','x','y'],[['x',...cov[0]],['y',...cov[1]]])]};},[12,14]);
}
if(PAGE.id==='S42'){
lab('omni','Omni-wheel kinematics','Resolve (vx,vy) into each wheel’s driven and free-rolling directions. Defaults match the notebook: R = 0.5 m and wheel radius r = 0.2 m.',[slider('vx','vx (m/s)',.3,-1,1,.01),slider('vy','vy (m/s)',.1,-1,1,.01),slider('r','Wheel radius (m)',.2,.05,.4,.01)],s=>{const rows=range(3,i=>{const t=i*2*Math.PI/3,para=-s.vx*Math.sin(t)+s.vy*Math.cos(t),perp=s.vx*Math.cos(t)+s.vy*Math.sin(t);return[i,para,perp,para/s.r];}),circle=range(101,i=>[.5*Math.cos(i*Math.PI/50),.5*Math.sin(i*Math.PI/50)]),lines=[series('Chassis',circle),series('Body velocity',[[0,0],[s.vx,s.vy]])];rows.forEach((r,i)=>{const t=i*2*Math.PI/3,p=[.5*Math.cos(t),.5*Math.sin(t)];lines.push(series('Wheel '+i+' driven velocity',[p,L.add(p,[-Math.sin(t)*r[1],Math.cos(t)*r[1]])]));});return {charts:[xy('Velocity decomposition',lines,'x (m); velocity vectors scaled by 1 s','y (m)',{equal:true})],tables:[table('Wheel velocities',['Wheel','Parallel (m/s)','Perpendicular (m/s)','Angular speed (rad/s)'],rows)]};},[9,15,17,19,21]);
lab('motion','Gaussian motion model','Apply the four controls (2,0),(2,0),(0,2),(0,2) from the notebook and see uncertainty accumulate.',[slider('step','Controls applied',4,0,4),slider('sigma','Motion standard deviation (m)',.2,.01,2,.01),slider('N','Samples',200,20,1000,20),seed()],s=>{const u=[[2,0],[2,0],[0,2],[0,2]],means=[[20,10]];range(s.step,i=>means.push(L.add(means.at(-1),u[i])));const variance=.25+s.step*s.sigma**2,r=L.rng(s.seed),samples=range(s.N,()=>sample2(r,means.at(-1),[[variance,0],[0,variance]]));return {metrics:[['Mean position',means.at(-1).join(', ')],['Position variance (m²)',variance],['Prior error at (19,12)',10]],charts:[xy('Expected trajectory and endpoint samples',[series('Mean',means,'both'),series('Endpoint samples',samples,'scatter')],'x (m)','y (m)',{equal:true})],text:'Initial σ = 0.5 m. Independent process noise adds σ² to each coordinate variance per action; the example whitened prior error is (−2,4), giving ½‖e‖² = 10.'};},[31,35,39]);
}
if(PAGE.id==='S43'){
lab('rfid','RFID range likelihood','Start at (20.5,7.5), as in the notebook, and compare range to beacon 0 with the nearest beacon. The reader’s maximum range is 8 m.',[slider('x','Robot x (m)',20.5,0,99,.5),slider('y','Robot y (m)',7.5,0,49,.5),slider('sigma','Range noise σ (m)',1,.2,3,.1)],s=>{const p=[s.x,s.y],r0=L.norm(L.sub(p,MAP.beacons[0])),nearest=closestBeacon(p);return {metrics:[['Range to beacon 0',r0<=8?fmt(r0)+' m':'Out of range'],['Nearest detectable beacon',nearest.index<0?'None':nearest.index],['Nearest range',nearest.index<0?'Out of range':fmt(nearest.range)+' m']],charts:[heat('Likelihood of the nearest-beacon observation',mapGrid(q=>{const rs=MAP.beacons.map(b=>L.norm(L.sub(q,b)));if(nearest.index<0)return Math.min(...rs)>8?1:0;const d=rs[nearest.index];return d>8?0:Math.exp(-.5*((d-nearest.range)/s.sigma)**2);})),xy('Robot and beacon positions',[series('Beacons',MAP.beacons,'scatter'),series('Robot',[p],'scatter')],'x (m)','y (m)',{equal:true,xlim:[0,100],ylim:[0,50]})]};},[25,27,29,33,35]);
lab('proximity','Proximity sensor','Inspect the exact warehouse occupancy map and the ON/OFF likelihood arrays used by the notebook.',[select('reading','Map or measurement','off',[['base','Occupancy map'],['on','Proximity = ON'],['off','Proximity = OFF']])],s=>({charts:[heat('Warehouse '+s.reading,s.reading==='base'?MAP.base:s.reading==='on'?MAP.proximity:MAP.off,{min:0,max:1})]}),[8,10,16,18]);
lab('gps','GPS-like likelihood','The sensor reports centimeters: z = 100x + noise, with σ = 30 cm. See how a measurement becomes a likelihood in meters.',[slider('zx','Measured x (cm)',2000,0,10000,10),slider('zy','Measured y (cm)',1000,0,5000,10),slider('sigma','Measurement σ (cm)',30,5,300,5)],s=>({metrics:[['Likelihood center (m)',`${s.zx/100}, ${s.zy/100}`],['Equivalent σ (m)',s.sigma/100]],charts:[xy('x-coordinate likelihood',[series('Likelihood',range(201,i=>{const x=s.zx/100+(i-100)*s.sigma/2000;return [x,L.gaussian(s.zx,100*x,s.sigma)];}))],'Position x (m)','p(zx | x) (cm⁻¹)')]}),[41,43,44]);
}
const filterCache=new Map();
function gridFilter(sigma,updates){const key=sigma+':'+updates;if(filterCache.has(key))return filterCache.get(key);let p=mapGrid(q=>gauss2(q,[10,6],[[25,0],[0,25]]));const all=[];const normalizeGrid=a=>{const z=L.sum(a.flat());return a.map(r=>r.map(v=>v/z));};if(updates)p=normalizeGrid(p.map((r,i)=>r.map((v,j)=>v*MAP.off[i][j])));all.push(normalizeGrid(p));const h=Math.ceil(6*sigma),kernel=range(2*h+1,i=>L.gaussian(i-h,0,sigma));for(let t=1;t<14;t++){const u=L.sub(warehousePath[t],warehousePath[t-1]),tmp=range(50,()=>Array(100).fill(0)),next=range(50,()=>Array(100).fill(0));for(let i=0;i<50;i++)for(let j=0;j<100;j++)if(p[i][j]>1e-5)for(let k=-h;k<=h;k++){const x=j+u[0]+k;if(x>=0&&x<100)tmp[i][x]+=p[i][j]*kernel[k+h];}for(let i=0;i<50;i++)for(let j=0;j<100;j++)if(tmp[i][j])for(let k=-h;k<=h;k++){const y=i+u[1]+k;if(y>=0&&y<50)next[y][j]+=tmp[i][j]*kernel[k+h];}p=normalizeGrid(next);if(updates)p=normalizeGrid(p.map((r,i)=>r.map((v,j)=>v*MAP.off[i][j])));all.push(p);}if(filterCache.size>8)filterCache.clear();filterCache.set(key,all);return all;}
if(PAGE.id==='S44'){
lab('markov','Markov localization','Follow the notebook trajectory from (10,6) to (50,31). Compare prediction alone with repeated proximity-OFF updates.',[slider('step','Time index (0 = prior)',13,0,13),slider('sigma','Motion σ (m)',2,.5,3,.5),select('updates','Sensor updates','on',[['on','Proximity OFF at each step'],['off','Prediction only']])],s=>{const p=gridFilter(s.sigma,s.updates==='on')[s.step],mean=[0,0];p.forEach((r,i)=>r.forEach((v,j)=>{mean[0]+=v*(j+MAP.mapOrigin[0]);mean[1]+=v*(i+MAP.mapOrigin[1]);}));return {metrics:[['Truth position',warehousePath[s.step].join(', ')],['Posterior mean',mean.map(fmt).join(', ')],['Probability mass',L.sum(p.flat())]],charts:[heat('Position density',p,{path:warehousePath.slice(0,s.step+1)})],text:'Same 100 × 50 grid, 10⁻⁵ prior-mass threshold, and σ = 2 m default as the notebook. Separable convolution truncates the Gaussian at six standard deviations for browser performance.'};},[8,16,18,20,23]);
lab('particles','Monte Carlo localization','Resample, predict, and weight particles using the warehouse’s proximity-OFF measurements. Add the notebook’s RFID model to reduce ambiguity.',[slider('step','Time index',13,0,13),slider('N','Particles',500,100,2000,100),select('prior','Initial belief','local',[['local','Gaussian: mean (10,6), covariance 25I'],['global','Uniform over the warehouse']]),select('rfid','RFID update','no',[['no','Proximity only'],['yes','Proximity + nearest RFID']]),seed()],s=>{const r=L.rng(s.seed),off=p=>{const x=Math.round(p[0]),y=Math.round(p[1]);return x<0||x>99||y<0||y>49?0:MAP.off[y][x];};let particles=range(s.N,()=>s.prior==='local'?[10+5*r.normal(),6+5*r.normal()]:[100*r(),50*r()]),weights=[];for(let k=0;k<=s.step;k++){if(k){const prev=particles,u=L.sub(warehousePath[k],warehousePath[k-1]),cdf=[];let c=0;L.normalize(weights).forEach(v=>cdf.push(c+=v));const pick=()=>{const u=r();let lo=0,hi=cdf.length-1;while(lo<hi){const mid=(lo+hi)>>1;if(u<cdf[mid])hi=mid;else lo=mid+1;}return lo;};particles=range(s.N,()=>L.add(L.add(prev[pick()],u),[2*r.normal(),2*r.normal()]));}const z=closestBeacon(warehousePath[k]);weights=particles.map(p=>{let w=off(p);if(s.rfid==='yes'){const q=closestBeacon(p);if(z.index<0)w*=+(q.index<0);else{const dist=L.norm(L.sub(p,MAP.beacons[z.index]));w*=dist>8?0:Math.exp(-.5*(dist-z.range)**2);}}return w;});if(!L.sum(weights))throw Error('No particles explain this observation. Increase the particle count or change the seed.');}const p=L.normalize(weights),mean=[L.dot(p,particles.map(p=>p[0])),L.dot(p,particles.map(p=>p[1]))];return {metrics:[['Weighted mean',mean.map(fmt).join(', ')],['Effective sample size',1/L.dot(p,p)]],charts:[xy('Particle approximation',[series('Particles with nonzero likelihood',particles.filter((_,i)=>weights[i]>1e-8),'scatter'),series('Truth trajectory',warehousePath.slice(0,s.step+1),'both')],'x (m)','y (m)',{equal:true,xlim:[0,100],ylim:[0,50]})],text:'Seeded browser draws use the same models, not the notebook’s unseeded sample realization. RFID updates are applied at the current time index.'};},[35,37,39,43,51,59]);
lab('least-squares','Three constraints, two unknowns','Reproduce A = [[1,0],[-1,1],[0,1]] and b = [3,5,7]. See why inconsistent measurements require a compromise.',[input('b','Measurements b','3,5,7')],s=>{const A=[[1,0],[-1,1],[0,1]],b=vector(s.b,3),x=L.ls(A,b),r=L.sub(L.mv(A,x),b);return {metrics:[['x₁',x[0]],['x₂',x[1]],['½ sum of squared residuals',L.dot(r,r)/2]],charts:[bar('Residuals A x − b',['x₁ − b₁','x₂ − x₁ − b₂','x₂ − b₃'],r)],tables:[table('Constraints',['A row','b','Prediction'],A.map((row,i)=>[row.join(', '),b[i],L.dot(row,x)]))]};},[70,72]);
lab('kalman','Kalman smoothing','Estimate all 14 positions jointly using the notebook’s prior, odometry, and centimeter-valued GPS model.',[slider('motion','Motion σ (m)',2,.2,5,.1),slider('gps','GPS σ (cm)',30,5,300,5),seed()],s=>{const r=L.rng(s.seed),z=warehousePath.map(p=>p.map(v=>100*v+s.gps*r.normal())),n=14,A=[],bs=[[],[]];let row=Array(n).fill(0);row[0]=2;A.push(row);bs.forEach((b,j)=>b.push(2*warehousePath[0][j]));for(let k=1;k<n;k++){row=Array(n).fill(0);row[k]=1/s.motion;row[k-1]=-1/s.motion;A.push(row);bs.forEach((b,j)=>b.push((warehousePath[k][j]-warehousePath[k-1][j])/s.motion));}for(let k=0;k<n;k++){row=Array(n).fill(0);row[k]=100/s.gps;A.push(row);bs.forEach((b,j)=>b.push(z[k][j]/s.gps));}const xyopt=L.tr(bs.map(b=>L.ls(A,b)));return {metrics:[['Position RMSE (m)',Math.sqrt(L.sum(xyopt.map((p,i)=>L.dot(L.sub(p,warehousePath[i]),L.sub(p,warehousePath[i]))))/n)]],charts:[xy('Jointly smoothed trajectory',[series('Ground truth',warehousePath),series('GPS converted to meters',z.map(p=>L.scale(p,.01)),'scatter'),series('Smoothed',xyopt,'both')],'x (m)','y (m)',{equal:true}),heat('Whitened Jacobian magnitude',A.map(r=>r.map(Math.abs)),{caption:'One coordinate block: prior, motion, and measurement rows'})]};},[77,79,83,85,88]);
}
if(PAGE.id==='S45'){
lab('value-map','Warehouse value iteration','Propagate the goal reward through the notebook’s 50 × 100 map. The goal is row 35, column 50; proximity incurs a penalty on departure and arrival.',[slider('steps','Bellman iterations',120,0,180,5),slider('gamma','Discount γ',.975,.8,.995,.005),slider('penalty','Proximity penalty',50,0,100,5)],s=>{let V=range(50,()=>Array(100).fill(0)),error=0;const goal=[35,50];range(s.steps,()=>{const next=range(50,()=>Array(100).fill(0));error=0;for(let i=0;i<50;i++)for(let j=0;j<100;j++){if((i===35&&j===50)||MAP.base[i][j])continue;const dest=[[i,Math.max(0,j-1)],[i,Math.min(99,j+1)],[Math.max(0,i-1),j],[Math.min(49,i+1),j]];next[i][j]=Math.max(...dest.map(([y,x])=>(y===35&&x===50?100:0)-(MAP.proximity[i][j]?s.penalty:0)-(MAP.proximity[y][x]?s.penalty:0)+s.gamma*V[y][x]));error=Math.max(error,Math.abs(next[i][j]-V[i][j]));}V=next;});return {metrics:[['Last update max |ΔV|',error],['Goal (x,y)','50,35']],charts:[heat('Value function',V,{caption:'Notebook row/column convention · goal is absorbing with V = 0'})],text:'As in the supplied Q_value code, rewards are collected only on arrival at the goal, and occupied current states have value zero. No extra collision rules are silently added.'};},[9,11]);
}
if(PAGE.id==='S46'){
lab('scalar','Identify a scalar sensor','Generate measurements with C = 100 cm/m and σ = 30 cm, then fit through the origin using Σxz / Σx².',[slider('N','Samples',200,10,500,10),slider('C','True scale (cm/m)',100,50,150),slider('sigma','Noise σ (cm)',30,0,200,5),seed()],s=>{const r=L.rng(s.seed),x=range(s.N,()=>100*r()),z=x.map(v=>s.C*v+s.sigma*r.normal()),c=L.dot(x,z)/L.dot(x,x),variance=L.sum(x.map((v,i)=>(c*v-z[i])**2))/(s.N-1);return {metrics:[['Estimated C (cm/m)',c],['Estimated σ (cm)',Math.sqrt(variance)]],charts:[xy('Position and sensor reading',[series('Samples',x.map((v,i)=>[v,z[i]]),'scatter'),series('Least-squares fit',[[0,0],[100,100*c]])],'Position (m)','Measurement (cm)')]};},[10,12,14]);
lab('matrix','Identify a multivariate model','Fit the notebook’s 3 × 2 sensor matrix, or identify both motion matrices A and B from position and control data.',[select('model','Model','sensor',[['sensor','Sensor H = [[10,20],[30,40],[50,60]]'],['motion','Motion A = I, B = I']]),slider('N','Samples (sensor 200; motion 500)',200,20,500,20),seed()],s=>{const r=L.rng(s.seed),motion=s.model==='motion',truth=motion?[[1,0,1,0],[0,1,0,1]]:[[10,20],[30,40],[50,60]],sigma=motion?2:30,X=range(s.N,()=>motion?[100*r(),50*r(),5*r.normal(),5*r.normal()]:[100*r(),50*r()]),Z=X.map(x=>L.mv(truth,x).map(z=>z+sigma*r.normal())),fit=L.tr(Z).map(z=>L.ls(X,z)),rss=L.sum(Z.map((z,i)=>L.dot(L.sub(z,L.mv(fit,X[i])),L.sub(z,L.mv(fit,X[i]))))),dof=s.N*truth.length-truth.length*truth[0].length;return {metrics:[['Residual σ estimate',Math.sqrt(rss/dof)]],tables:[table('True matrix',['Row',...range(truth[0].length,i=>(motion?['Ax','Ay','Bu','Bv'][i]:['x','y'][i]))],truth.map((r,i)=>[i,...r])),table('Estimated matrix',['Row',...range(truth[0].length,String)],fit.map((r,i)=>[i,...r]))],text:'The motion example uses σ = 2 m and Gaussian controls with σ = 5 m. Select 500 samples to match its notebook sample count.'};},[20,22,24,27,30,32]);
}
