'use strict';
const L=MathLab, experiments=[];
const C=['#985218','#247780','#7050a0','#427348','#ba424c','#3a6c9a'];
const $=id=>document.getElementById(id), fmt=x=>typeof x==='number'?(!Number.isFinite(x)?'—':Math.abs(x)>0&&Math.abs(x)<.0001?x.toExponential(3):Number(x.toFixed(5)).toString()):String(x);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=x=>(x*100).toFixed(1)+'%', deg=x=>x*Math.PI/180;
const range=(n,f=i=>i)=>Array.from({length:n},(_,i)=>f(i));
const vector=(s,n=null)=>{const a=String(s).trim().split(/[\s,;/]+/).map(Number);if(!a.length||a.some(v=>!Number.isFinite(v))||(n&&a.length!==n))throw Error(`Enter ${n||'a list of'} finite numbers separated by commas.`);return a;};
const positive=a=>{if(a.some(v=>v<0))throw Error('Weights and counts must be nonnegative.');return a;};
const slider=(key,label,value,min,max,step=1)=>({key,label,value,min,max,step,type:'range'});
const select=(key,label,value,options)=>({key,label,value,options,type:'select'});
const input=(key,label,value)=>({key,label,value,type:'text'});
const seed=()=>slider('seed','Sample seed',42,1,999,1);
const lab=(id,title,description,controls,run,cells,note='',mode='live')=>experiments.push({id,title,description,controls,run,cells,note,mode});
const xy=(title,series,xlabel='x',ylabel='y',extra={})=>({type:'xy',title,series,xlabel,ylabel,...extra});
const series=(name,points,mode='line',color=null)=>({name,points,mode,color});
const bar=(title,labels,values,extra={})=>({type:'bar',title,labels,values,...extra});
const table=(title,headers,rows)=>({title,headers,rows});
const heat=(title,values,extra={})=>({type:'heat',title,values,...extra});
function chart(ch){if(ch.type==='color'){const rgb=ch.rgb.map(v=>Math.round(255*Math.max(0,Math.min(1,v))));return `<div class="color-swatch" style="background:rgb(${rgb.join(',')})" role="img" aria-label="Rendered RGB: ${esc(ch.rgb.map(fmt).join(', '))}"></div><p>RGB = (${ch.rgb.map(fmt).join(', ')})</p>`;}if(ch.type==='image')return `<figure><img class="saved-image" src="${ch.src}" alt="${esc(ch.title)}"><figcaption>${esc(ch.caption||'Saved notebook output')}</figcaption></figure>`;
 let b='',W=760,H=380,left=62,right=25,top=20,bottom=54,pw=W-left-right,ph=H-top-bottom;
 const text=(x,y,t,attrs='')=>`<text x="${x}" y="${y}" ${attrs}>${esc(t)}</text>`;
 const line=(x1,y1,x2,y2,attrs='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" ${attrs}/>`;
 if(ch.type==='bar'){H=Math.max(240,ch.labels.length*39+55);left=150;right=110;pw=W-left-right;const lo=Math.min(0,...ch.values),hi=ch.max??(Math.max(0,...ch.values,...(ch.compare||[]))*1.08||1),span=hi-lo||1,x=v=>left+(v-lo)/span*pw;
 for(let k=0;k<=4;k++){const v=lo+span*k/4;b+=line(x(v),10,x(v),H-35,'stroke="#d9d5c9"')+text(x(v),H-12,ch.percent?pct(v):fmt(v),'text-anchor="middle"');}
 ch.labels.forEach((s,i)=>{const y=17+i*(H-55)/ch.labels.length;b+=text(left-10,y+18,s,'text-anchor="end"');if(ch.compare)b+=`<rect x="${x(Math.min(0,ch.compare[i]))}" y="${y}" width="${Math.abs(ch.compare[i])/span*pw}" height="25" fill="none" stroke="${C[i%C.length]}"/>`;b+=`<rect x="${x(Math.min(0,ch.values[i]))}" y="${y+6}" width="${Math.abs(ch.values[i])/span*pw}" height="13" fill="${C[i%C.length]}"/>`+text(W-right+12,y+18,ch.percent?pct(ch.values[i]):fmt(ch.values[i]));});
 }else if(ch.type==='xy'){
 const points=ch.series.flatMap(s=>s.points).filter(p=>p.every(Number.isFinite));if(!points.length)return '<p>No finite points for these settings.</p>';
 let xs=ch.xlim||[Math.min(...points.map(p=>p[0])),Math.max(...points.map(p=>p[0]))],ys=ch.ylim||[Math.min(...points.map(p=>p[1])),Math.max(...points.map(p=>p[1]))];xs=[...xs];ys=[...ys];if(xs[0]===xs[1]){xs[0]-=1;xs[1]+=1;}if(ys[0]===ys[1]){ys[0]-=1;ys[1]+=1;}if(!ch.ylim){const p=(ys[1]-ys[0])*.08;ys[0]-=p;ys[1]+=p;}if(ch.equal){const dx=xs[1]-xs[0],dy=ys[1]-ys[0];if(dx/dy<pw/ph){const p=(dy*pw/ph-dx)/2;xs=[xs[0]-p,xs[1]+p];}else{const p=(dx*ph/pw-dy)/2;ys=[ys[0]-p,ys[1]+p];}}
 const x=v=>left+(v-xs[0])/(xs[1]-xs[0])*pw,y=v=>top+ph-(v-ys[0])/(ys[1]-ys[0])*ph;
 for(let j=0;j<=4;j++){const xx=xs[0]+(xs[1]-xs[0])*j/4,yy=ys[0]+(ys[1]-ys[0])*j/4;b+=line(left,y(yy),W-right,y(yy),'stroke="#d9d5c9"')+text(left-9,y(yy)+5,fmt(yy),'text-anchor="end"')+text(x(xx),H-30,fmt(xx),'text-anchor="middle"');}
 for(const [i,s]of ch.series.entries()){const p=s.points.filter(p=>p.every(Number.isFinite)),color=s.color||C[i%C.length];if(s.mode==='segments'){for(let k=0;k+1<p.length;k+=2)b+=line(x(p[k][0]),y(p[k][1]),x(p[k+1][0]),y(p[k+1][1]),`stroke="${color}" stroke-width="1.2" opacity=".6"`);}else if(s.mode!=='scatter')b+=`<polyline points="${p.map(p=>`${x(p[0])},${y(p[1])}`).join(' ')}" fill="none" stroke="${color}" stroke-width="2.2" ${s.mode==='dashed'?'stroke-dasharray="5 4"':''}/>`;if(s.mode==='scatter'||s.mode==='both')p.forEach(p=>b+=`<circle cx="${x(p[0])}" cy="${y(p[1])}" r="${s.radius||2.8}" fill="${color}" opacity=".75"><title>${esc(s.name)}: ${fmt(p[0])}, ${fmt(p[1])}</title></circle>`);}
 if(ch.marker!==undefined)b+=line(x(ch.marker),top,x(ch.marker),top+ph,'stroke="#586668" stroke-dasharray="4 4"');b+=text(left+pw/2,H-4,ch.xlabel,'text-anchor="middle"')+text(left,14,ch.ylabel);
 }else if(ch.type==='heat'){const a=ch.values,n=a.length,m=a[0].length,max=ch.max??Math.max(...a.flat()),min=ch.min??Math.min(...a.flat());H=ch.height||400;const h=H-58,w=W-75;for(let i=0;i<n;i++)for(let j=0;j<m;j++){const v=a[i][j],t=Math.max(0,Math.min(1,(v-min)/(max-min||1)));const color=ch.gray?`rgb(${255-Math.round(t*225)},${255-Math.round(t*225)},${255-Math.round(t*225)})`:`rgb(${Math.round(246-210*t)},${Math.round(243-132*t)},${Math.round(230-109*t)})`;b+=`<rect x="${50+j*w/m}" y="${15+i*h/n}" width="${w/m+.2}" height="${h/n+.2}" fill="${color}"><title>row ${i}, column ${j}: ${fmt(v)}</title></rect>`;}if(ch.path)b+=`<polyline points="${ch.path.map(p=>`${50+p[0]/m*w},${15+p[1]/n*h}`).join(' ')}" fill="none" stroke="#c33f41" stroke-width="2.5"/>`;b+=text(50,H-16,ch.caption||`Scale: ${fmt(min)} to ${fmt(max)} · rows increase downward`);}
 return `<div class="plot-scroll"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(ch.title)}"><title>${esc(ch.title)}</title>${b}</svg></div>`+(ch.type==='xy'?`<div class="legend">${ch.series.map((s,i)=>`<span><i style="background:${s.color||C[i%C.length]}"></i>${esc(s.name)}</span>`).join('')}</div>`:'');
}
function renderTable(t){return `<div class="table-wrap"><table><caption>${esc(t.title)}</caption><thead><tr>${t.headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr>${r.map((v,i)=>`<${i?'td':'th scope="row"'}>${esc(fmt(v))}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function mount(){let active=0,states=experiments.map(e=>Object.fromEntries(e.controls.map(c=>[c.key,c.value]))),timer;
 const tabs=$('tabs');tabs.innerHTML=experiments.map((e,i)=>`<button id="tab-${i}" role="tab" aria-controls="experiment" aria-selected="${i===0}" tabindex="${i===0?0:-1}">${esc(e.title)}</button>`).join('');
 function show(i,focus=false){clearTimeout(timer);active=i;const e=experiments[i],s=states[i];[...tabs.children].forEach((b,j)=>{b.setAttribute('aria-selected',String(i===j));b.tabIndex=i===j?0:-1;});$('experiment').setAttribute('aria-labelledby','tab-'+i);if(focus)tabs.children[i].focus();$('experiment-title').textContent=e.title;$('description').textContent=e.description;$('note').textContent=e.note;$('note').hidden=!e.note||e.mode==='recorded';
 const recorded=e.mode==='recorded';$('recorded-notice').hidden=!recorded;$('run').hidden=recorded;$('reset').textContent=recorded?'Default figure':'Notebook defaults';$('controls-title').textContent=recorded?'Saved figures':'The experiment';
 $('controls').innerHTML=e.controls.map(c=>{const id='control-'+c.key;return `<div class="control"><label for="${id}">${esc(c.label)}${c.type==='range'?`<output for="${id}">${esc(s[c.key])}</output>`:''}</label>${c.type==='select'?`<select id="${id}">${c.options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${String(v)===String(s[c.key])?'selected':''}>${esc(t)}</option>`;}).join('')}</select>`:`<input id="${id}" type="${c.type}" value="${esc(s[c.key])}" ${c.type==='range'?`min="${c.min}" max="${c.max}" step="${c.step}"`:''}>`}</div>`;}).join('');
 e.controls.forEach(c=>{const el=$('control-'+c.key);el.addEventListener(c.type==='select'?'change':'input',()=>{s[c.key]=c.type==='range'?el.valueAsNumber:el.value;if(c.type==='range')el.previousElementSibling.querySelector('output').textContent=el.value;clearTimeout(timer);timer=setTimeout(update,c.type==='text'?250:35);});});
 $('source').innerHTML=e.cells.map(i=>`<h4>Notebook code cell ${i}</h4><pre><code>${esc(PAGE.code[i]||'See the source notebook.')}</code></pre>`).join('');update();}
 function update(){clearTimeout(timer);try{const e=experiments[active],o=e.run(states[active]);$('error').hidden=true;$('metrics').innerHTML=(o.metrics||[]).map(([k,v])=>`<div class="metric"><span>${esc(k)}</span><strong>${esc(fmt(v))}</strong></div>`).join('');$('results').innerHTML=(o.charts||[]).map(ch=>`<article class="chart-card"><h3>${esc(ch.title)}</h3>${chart(ch)}</article>`).join('')+(o.tables||[]).map(t=>`<article class="chart-card">${renderTable(t)}</article>`).join('')+(o.text?`<p class="explanation">${esc(o.text)}</p>`:'');window.APPLET_LAST_RESULT=o;}catch(err){$('error').textContent=err.message;$('error').hidden=false;$('results').innerHTML='';$('metrics').innerHTML='';}}
 [...tabs.children].forEach((b,i)=>{b.addEventListener('click',()=>show(i));b.addEventListener('keydown',ev=>{let j;if(ev.key==='ArrowRight')j=(i+1)%experiments.length;if(ev.key==='ArrowLeft')j=(i+experiments.length-1)%experiments.length;if(ev.key==='Home')j=0;if(ev.key==='End')j=experiments.length-1;if(j!==undefined){ev.preventDefault();show(j,true);}});});$('reset').addEventListener('click',()=>{states[active]=Object.fromEntries(experiments[active].controls.map(c=>[c.key,c.value]));show(active);});$('run').addEventListener('click',update);window.APPLET={experiments,states,show,update};show(0);
}
