const SORT={names:['cardboard','paper','can','scrap metal','bottle'],prior:[.2,.3,.25,.2,.05],cost:[[2,2,4,6,0],[1,1,0,0,2],[0,0,5,10,3],[1,1,1,1,1]],actions:['glass bin','metal bin','paper bin','nop'],weight:[[20,10],[5,5],[15,5],[150,100],[300,200]],conductivity:[[.99,.01],[.99,.01],[.1,.9],[.15,.85],[.95,.05]],detection:[[.02,.88,.1],[.02,.2,.78],[.33,.33,.34],[.33,.33,.34],[.95,.02,.03]]};
if(PAGE.id==='S21'){
lab('sampling','PMF → CDF → samples','Trace an inverse-CDF draw, then compare a simulated batch to the exact distribution.',[input('p','Relative category weights','200,300,250,200,50'),slider('u','Uniform draw u',.37,0,.999,.001),slider('N','Number of samples',1000,10,5000,10),seed()],s=>{const p=L.normalize(positive(vector(s.p,5))),cdf=p.map((_,i)=>L.sum(p.slice(0,i+1))),k=cdf.findIndex(v=>s.u<v),r=L.rng(s.seed),counts=Array(5).fill(0);range(s.N).forEach(()=>counts[r.pick(p)]++);return {metrics:[['Selected category',SORT.names[k]],['Exact P(can)',pct(p[2])],['Sample count',s.N]],charts:[bar('Exact probability and sample frequency',SORT.names,counts.map(n=>n/s.N),{percent:true,max:1,compare:p}),bar('Cumulative distribution',SORT.names,cdf,{percent:true,max:1})],tables:[table('Inverse-CDF intervals',['Category','Probability','Lower bound (inclusive)','Upper bound (exclusive)'],p.map((v,i)=>[SORT.names[i],pct(v),i?cdf[i-1]:0,cdf[i]]))],text:'Outlined bars are the exact PMF; filled bars are the sample frequency. This seed makes samples repeatable; the notebook uses unseeded draws.'};},[20,24,34,37,40]);
lab('spec','Normalize a specification','Explore the three-valued GTSAM distribution and its unnormalized 2/4/2 specification.',[input('p','Three weights','2,4,2')],s=>{const p=L.normalize(positive(vector(s.p,3)));return {charts:[bar('Normalized probabilities',['one','two','three'],p,{percent:true,max:1})],metrics:[['Total probability',L.sum(p)]]};},[45,49,53]);
}
if(PAGE.id==='S22'){
lab('cost','The cost of an action','The notebook’s four actions map uncertain categories to uncertain costs. Compare expected cost to the running sample average.',[select('action','Action','0',SORT.actions.map((a,i)=>[i,a])),slider('N','Trials',100,10,2000,10),seed()],s=>{const a=+s.action,cost=SORT.cost[a],r=L.rng(s.seed),expected=L.dot(cost,SORT.prior);let total=0;const trace=range(s.N,i=>{total+=cost[r.pick(SORT.prior)];return[i+1,total/(i+1)];}),cs=[...new Set(cost)].sort((a,b)=>a-b),ps=cs.map(v=>L.sum(SORT.prior.map((p,i)=>cost[i]===v?p:0)));return {metrics:[['Expected cost',expected],['Sample mean',total/s.N]],charts:[bar('Distribution over cost',cs.map(String),ps,{percent:true,max:1}),xy('Average cost over repeated trials',[series('Sample average',trace),series('Expected cost',[[1,expected],[s.N,expected]],'dashed')],'Trials','Cost')],tables:[table('Notebook cost table',['Action',...SORT.names,'Expected cost'],SORT.cost.map((row,i)=>[SORT.actions[i],...row,L.dot(row,SORT.prior)]))]};},[8,16,19]);
}
if(PAGE.id==='S23'){
lab('density','Conditional weight density','The original notebook widget: choose the category and inspect its Gaussian weight model.',[select('category','Category','2',SORT.names.map((n,i)=>[i,n]))],s=>{const [mu,sd]=SORT.weight[+s.category];return {metrics:[['Mean weight',mu+' g'],['Standard deviation',sd+' g']],charts:[xy('p(weight | category)',[series(SORT.names[+s.category],range(500,x=>[x,L.gaussian(x,mu,sd)]))],'Weight (g)','Density (g⁻¹)')],tables:[table('Other sensor distributions',['Output','Probability'],[['Conductivity = 0',pct(SORT.conductivity[+s.category][0])],['Conductivity = 1',pct(SORT.conductivity[+s.category][1])],...['bottle','cardboard','paper'].map((n,i)=>[n,pct(SORT.detection[+s.category][i])])])]};},[22,24]);
lab('gaussian','Shape a Gaussian','Start with the notebook’s 250 g mean and 50 g standard deviation, then change either parameter.',[slider('mu','Mean (g)',250,0,500),slider('sd','Standard deviation (g)',50,1,200)],s=>({metrics:[['Peak density',L.gaussian(s.mu,s.mu,s.sd)]],charts:[xy('Gaussian density',[series('Density',range(501,x=>[x,L.gaussian(x,s.mu,s.sd)]))],'Weight (g)','Density (g⁻¹)')]}),[17,19]);
lab('simulation','Simulate all three sensors','First draw a category from the notebook prior, then independently draw its conductivity, detection, and weight.',[slider('N','Objects',10,5,100,5),seed()],s=>{const r=L.rng(s.seed),rows=range(s.N,i=>{const c=r.pick(SORT.prior);return[i+1,SORT.names[c],r.pick(SORT.conductivity[c]),['bottle','cardboard','paper'][r.pick(SORT.detection[c])],SORT.weight[c][0]+SORT.weight[c][1]*r.normal()];});return {tables:[table('Simulated conveyor belt',['Object','True category','Conductivity','Detection','Weight (g)'],rows)],text:'The Gaussian model can produce negative weights. As in the notebook, this simulation does not truncate the Gaussian.'};},[26,28,30,32,33]);
}
if(PAGE.id==='S25'){
lab('decision','Which bin should we choose?','Compare a naive most-likely-bin rule, minimax, and minimum expected cost under the notebook’s prior or example posterior.',[select('belief','Belief','prior',[['prior','Notebook prior: 20/30/25/20/5'],['posterior','Notebook posterior: 20/30/10/10/30'],['custom','Custom weights below']]),input('p','Custom category weights','20,30,10,10,30'),slider('damage','Scrap metal → paper bin cost',10,0,30)],s=>{const p=s.belief==='prior'?SORT.prior:s.belief==='posterior'?[.2,.3,.1,.1,.3]:L.normalize(positive(vector(s.p,5))),cost=SORT.cost.map(r=>[...r]);cost[2][3]=s.damage;const expected=cost.map(r=>L.dot(r,p)),worst=cost.map(r=>Math.max(...r)),bin=[p[4],p[2]+p[3],p[0]+p[1],0];return {metrics:[['Minimum expected cost',SORT.actions[expected.indexOf(Math.min(...expected))]],['Minimax action',SORT.actions[worst.indexOf(Math.min(...worst))]],['Most likely bin',SORT.actions[bin.indexOf(Math.max(...bin))]]],charts:[bar('Expected cost',SORT.actions,expected),bar('Worst-case cost',SORT.actions,worst)],tables:[table('Costs conditioned on category',['Action',...SORT.names],cost.map((r,i)=>[SORT.actions[i],...r]))]};},[11,13,17]);
}
if(PAGE.id==='S26'){
lab('counts','Learn a categorical distribution','The 25 observations in the notebook produce counts 3/11/7/1/3. Add a pseudocount to see how smoothing changes the estimate.',[input('counts','Category counts','3,11,7,1,3'),slider('alpha','Pseudocount per category',1,0,10,.25)],s=>{const counts=positive(vector(s.counts,5)),raw=L.normalize(counts),p=L.normalize(counts.map(n=>n+s.alpha));return {metrics:[['Observations',L.sum(counts)],['Effective total',L.sum(counts)+5*s.alpha]],charts:[bar('Smoothed estimate (filled) vs. raw estimate (outlined)',SORT.names,p,{percent:true,max:1,compare:raw})],tables:[table('Estimated PMF',['Category','Count','Raw','Smoothed'],counts.map((n,i)=>[SORT.names[i],n,pct(raw[i]),pct(p[i])]))]};},[9,11,13,20,22]);
lab('conditional','Learn sensor conditionals','Normalize each observed row separately. A category with fewer examples has a less certain sensor model.',[select('category','Category','0',SORT.names.map((n,i)=>[i,n])),slider('alpha','Pseudocount',0,0,10,.5)],s=>{const binary=[[80,20],[40,60],[12,4],[100,150],[10,10]][+s.category],three=[[10,70,20],[20,20,60],[2,10,4],[100,100,50],[5,5,10]][+s.category];return {charts:[bar('Estimated conductivity',['0','1'],L.normalize(binary.map(n=>n+s.alpha)),{percent:true,max:1}),bar('Estimated three-valued sensor',['Value1','Value2','Value3'],L.normalize(three.map(n=>n+s.alpha)),{percent:true,max:1})],tables:[table('Observed counts',['Sensor','Counts'],[['Conductivity',binary.join(' / ')],['Three-valued',three.join(' / ')]]) ]};},[26,28]);
lab('fit','Fit a Gaussian from samples','Use the notebook’s mean 200 g, standard deviation 50 g, and 200 samples. Compare the generating model and fitted distribution.',[slider('N','Samples',200,5,1000,5),slider('mu','Generating mean (g)',200,50,350),slider('sd','Generating standard deviation (g)',50,1,100),seed()],s=>{const r=L.rng(s.seed),xs=range(s.N,()=>s.mu+s.sd*r.normal()),mu=L.sum(xs)/s.N,variance=L.sum(xs.map(x=>(x-mu)**2))/(s.N-1),sd=Math.sqrt(variance);return {metrics:[['Estimated mean',mu],['Unbiased variance',variance],['Estimated standard deviation',sd]],charts:[xy('Generating density and fitted density',[series('Generating density',range(401,x=>[x,L.gaussian(x,s.mu,s.sd)])),series('Fitted density',range(401,x=>[x,L.gaussian(x,mu,sd)]))],'Weight (g)','Density (g⁻¹)'),xy('Observed weights',[series('Samples',xs.map((x,i)=>[i+1,x]),'scatter')],'Sample','Weight (g)')],text:'Variance uses N − 1, exactly as in the notebook. The displayed seed determines this applet’s random realization.'};},[33,37,38,41,43]);
}
