const VAC={rooms:['Living Room','Kitchen','Office','Hallway','Dining Room'],actions:['L','R','U','D'],light:['dark','medium','light'],S:[[.1,.1,.8],[.1,.1,.8],[.2,.7,.1],[.8,.1,.1],[.1,.8,.1]],dest:[[0,1,0,3],[0,1,1,4],[2,3,2,2],[2,4,0,3],[3,4,1,4]]};
VAC.T=VAC.dest.map((aa,x)=>aa.map(y=>range(5,j=>x===y?+(j===x):(j===x?.2:j===y?.8:0))));VAC.R=range(5,()=>range(4,()=>[10,0,0,0,0]));
const roomOptions=VAC.rooms.map((n,i)=>[i,n]);
function tape(s){const a=String(s).toUpperCase().trim().split(/[ ,]+/).filter(Boolean).map(x=>VAC.actions.indexOf(x));if(!a.length||a.length>30||a.some(a=>a<0))throw Error('Enter 1–30 actions, each L, R, U, or D.');return a;}
function predict(p,a,T=VAC.T){return range(5,j=>L.sum(p.map((v,i)=>v*T[i][a][j])));}
function roomPlot(p,title='Belief over rooms'){return bar(title,VAC.rooms,p,{percent:true,max:1});}
if(PAGE.id==='S31'){
lab('state','A belief over rooms','The notebook begins with certainty that the robot is in the Office. Move probability between rooms to represent uncertainty.',[input('p','Room weights: living, kitchen, office, hallway, dining','0,0,1,0,0')],s=>{const p=L.normalize(positive(vector(s.p,5)));return {charts:[roomPlot(p)],metrics:[['Most probable room',VAC.rooms[p.indexOf(Math.max(...p))]],['Entropy (bits)',-L.sum(p.map(x=>x?x*Math.log2(x):0))]],tables:[table('State-space encoding',['Index','Room','Probability'],p.map((v,i)=>[i,VAC.rooms[i],pct(v)]))]};},[11,15,16]);
}
if(PAGE.id==='S32'){
lab('motion','Propagate a belief','Start in the Office and execute R,U, as in the notebook. Valid moves succeed with probability 0.8; otherwise the robot stays put.',[select('start','Starting room','2',roomOptions),input('actions','Action tape','R,U')],s=>{const aa=tape(s.actions);let p=range(5,i=>+(i===+s.start)),rows=[[0,'—',...p]];aa.forEach((a,k)=>{p=predict(p,a);rows.push([k+1,VAC.actions[a],...p]);});return {charts:[roomPlot(p,'Belief after the action tape')],tables:[table('Belief propagation',['Step','Action',...VAC.rooms],rows),table('One-step transition from starting room',['Action',...VAC.rooms],VAC.T[+s.start].map((r,i)=>[VAC.actions[i],...r]))],metrics:[['Actions applied',aa.length]]};},[11,27,33]);
lab('battery','Factor location and battery','The notebook models battery transitions full→half→empty with probability 0.1 at each step. The factored state has 5 × 3 possibilities.',[slider('steps','Time steps',2,0,30),input('actions','Location action tape (cycled)','R,U')],s=>{const aa=tape(s.actions);let p=[0,0,1,0,0],b=[1,0,0];range(s.steps,k=>{p=predict(p,aa[k%aa.length]);b=[.9*b[0],.1*b[0]+.9*b[1],.1*b[1]+b[2]];});return {charts:[roomPlot(p),bar('Battery distribution',['full','half','empty'],b,{percent:true,max:1})],tables:[table('Joint factored probability',['Room','full','half','empty'],p.map((v,i)=>[VAC.rooms[i],...b.map(w=>v*w)]))]};},[42,44]);
}
if(PAGE.id==='S33'){
lab('light','A light sensor model','Living Room and Kitchen have identical light distributions. A single observation cannot distinguish them without a prior.',[select('room','True room','2',roomOptions),slider('N','Sensor samples',1000,10,2000,10),seed()],s=>{const p=VAC.S[+s.room],r=L.rng(s.seed),n=[0,0,0];range(s.N,()=>n[r.pick(p)]++);return {charts:[bar('Observed frequency (filled) and sensor model (outlined)',VAC.light,n.map(x=>x/s.N),{percent:true,max:1,compare:p})],tables:[table('p(light level | room)',['Room',...VAC.light],VAC.S.map((r,i)=>[VAC.rooms[i],...r]))]};},[9]);
lab('dbn','Sample a dynamic Bayes net','An ancestral rollout follows the notebook’s Office prior and four R actions. Every state generates its own light reading.',[input('actions','Action tape','R,R,R,R'),seed()],s=>{const aa=tape(s.actions),r=L.rng(s.seed);let x=2;const rows=[[1,VAC.rooms[x],VAC.light[r.pick(VAC.S[x])],'—']];aa.forEach((a,k)=>{x=r.pick(VAC.T[x][a]);rows.push([k+2,VAC.rooms[x],VAC.light[r.pick(VAC.S[x])],VAC.actions[a]]);});return {tables:[table('States and observations',['Time','True room','Light reading','Previous action'],rows)],charts:[xy('Sampled state trajectory',[series('Room index',rows.map((r,i)=>[i+1,VAC.rooms.indexOf(r[1])]),'both')],'Time','Room index',{ylim:[0,4]})],text:'Change the seed to generate another trajectory from exactly the same transition and sensor probabilities.'};},[14,20]);
}
if(PAGE.id==='S34'){
lab('hmm','Infer the hidden trajectory','The notebook fixes actions R,U and measurements dark, medium, light. Compare the most likely complete path with marginal probabilities at each time.',[select('a1','Action 1','1',VAC.actions.map((n,i)=>[i,n])),select('a2','Action 2','2',VAC.actions.map((n,i)=>[i,n])),...range(3,i=>select('z'+i,'Light at time '+(i+1),String(i),VAC.light.map((n,j)=>[j,n])))],s=>{const h=L.hmm(VAC.T,VAC.S,[+s.a1,+s.a2],[+s.z0,+s.z1,+s.z2],[1,1,1,1,1]),best=h.paths[0];return {metrics:[['MAP path',best.xs.map(x=>VAC.rooms[x]).join(' → ')],['MAP factor score',best.p],['Posterior probability of path',pct(best.p/h.evidence)]],charts:h.marg.map((p,i)=>roomPlot(p,'Smoothed marginal at time '+(i+1))),tables:[table('Five most likely paths',['Time 1','Time 2','Time 3','Factor score','Posterior'],h.paths.slice(0,5).map(p=>[...p.xs.map(x=>VAC.rooms[x]),p.p,pct(p.p/h.evidence)]))],text:'The factor score uses the notebook’s unnormalized all-ones prior. Dividing all path scores by their sum recovers posterior probabilities. Marginal modes need not form the MAP path.'};},[28,30,35,43,49,54]);
}
if(PAGE.id==='S35'){
lab('rewards','Immediate reward','Reward is 10 when the next state is the Living Room and zero otherwise. Evaluate every action from the selected room.',[select('room','Current room','1',roomOptions)],s=>({charts:[bar('Expected immediate reward',VAC.actions,VAC.T[+s.room].map((p,a)=>L.dot(p,VAC.R[+s.room][a])))],tables:[table('Transition probabilities',['Action',...VAC.rooms],VAC.T[+s.room].map((p,a)=>[VAC.actions[a],...p]))]}),[13,15,17,21]);
lab('policy','Evaluate a policy','Solve (I − γTπ)V = Rπ for the notebook’s reasonable policy, or compare it with always moving right.',[select('policy','Policy','reasonable',[['reasonable','U,L,R,U,L (notebook)'],['right','Always R'],['custom','Custom policy below']]),input('pi','One action per room','U,L,R,U,L'),slider('gamma','Discount γ',.9,0,.99,.01)],s=>{const pi=s.policy==='reasonable'?[2,0,1,2,0]:s.policy==='right'?[1,1,1,1,1]:tape(s.pi);if(pi.length!==5)throw Error('A policy needs exactly one action for each of the five rooms.');const V=L.policyValue(VAC.T,VAC.R,pi,s.gamma);return {charts:[bar('Exact discounted value',VAC.rooms,V)],tables:[table('Policy and value',['Room','Action','Vπ'],V.map((v,i)=>[VAC.rooms[i],VAC.actions[pi[i]],v]))],text:'The Living Room value is 100 at γ = 0.9 under this policy: repeatedly staying there earns 10 + 9 + 8.1 + … .'};},[42,60,62,64]);
lab('rollouts','Control-tape rollouts','Compare sampled reward with the exact expectation for the notebook tape R,U,L,L, starting in the Office.',[input('actions','Action tape','R,U,L,L'),slider('gamma','Discount γ',1,0,1,.05),slider('N','Rollouts',100,10,2000,10),seed()],s=>{const aa=tape(s.actions),r=L.rng(s.seed);let p=[0,0,1,0,0],expected=0;aa.forEach((a,k)=>{p=predict(p,a);expected+=s.gamma**k*10*p[0];});const rewards=range(s.N,()=>{let x=2,reward=0;aa.forEach((a,k)=>{x=r.pick(VAC.T[x][a]);reward+=s.gamma**k*(x===0?10:0);});return reward;});let total=0;return {metrics:[['Exact expected utility',expected],['Monte Carlo estimate',L.sum(rewards)/s.N]],charts:[xy('Convergence of the rollout average',[series('Sample average',rewards.map((v,i)=>{total+=v;return[i+1,total/(i+1)];})),series('Exact expectation',[[1,expected],[s.N,expected]],'dashed')],'Rollouts','Discounted utility')]};},[32,34,38]);
}
if(PAGE.id==='S36'){
lab('value','Value iteration','Start at V = 100 in every room, as in the notebook. Repeated Bellman backups reveal the optimal value and greedy policy.',[slider('steps','Bellman backups',10,0,100),slider('initial','Initial value',100,0,120),slider('gamma','Discount γ',.9,0,.99,.01)],s=>{let V=Array(5).fill(s.initial),trace=[];range(s.steps,k=>{const next=L.qValues(VAC.T,VAC.R,V,s.gamma).map(q=>Math.max(...q));trace.push([k+1,Math.max(...L.sub(next,V).map(Math.abs))]);V=next;});const Q=L.qValues(VAC.T,VAC.R,V,s.gamma);return {charts:[bar('Current value function',VAC.rooms,V),...(trace.length?[xy('Bellman update size',[series('Largest change',trace)],'Iteration','Max |ΔV|')]:[])],tables:[table('Action values and greedy policy',['Room',...VAC.actions,'Greedy action'],Q.map((q,i)=>[VAC.rooms[i],...q,VAC.actions[q.indexOf(Math.max(...q))]]))]};},[10,28,30,32]);
lab('policy-iteration','Policy iteration','Alternate exact policy evaluation and greedy improvement, starting with the notebook’s always-right policy.',[slider('steps','Policy improvements',2,0,8),slider('gamma','Discount γ',.9,0,.99,.01)],s=>{let pi=[1,1,1,1,1],rows=[];range(s.steps+1,k=>{const V=L.policyValue(VAC.T,VAC.R,pi,s.gamma);rows.push([k,pi.map(a=>VAC.actions[a]).join(','),...V]);pi=L.qValues(VAC.T,VAC.R,V,s.gamma).map(q=>q.indexOf(Math.max(...q)));});return {tables:[table('Evaluate, then improve',['Iteration','Evaluated policy',...VAC.rooms],rows)],charts:[bar('Last evaluated value function',VAC.rooms,rows.at(-1).slice(2))]};},[16,18,20,21,23]);
lab('q-learning','Learn from experience','Explore from the Living Room with random actions, then apply the notebook’s Q-learning update. More samples improve coverage; a constant learning rate still introduces variability.',[slider('N','Transition samples',499,20,10000),slider('alpha','Learning rate α',.5,.01,1,.01),slider('gamma','Discount γ',.9,0,.99,.01),seed()],s=>{const r=L.rng(s.seed),Q=range(5,()=>Array(4).fill(0)),counts=range(5,()=>range(4,()=>Array(5).fill(0)));let x=0;range(s.N,()=>{const a=Math.floor(r()*4),y=r.pick(VAC.T[x][a]),reward=y===0?10:0;counts[x][a][y]++;Q[x][a]=(1-s.alpha)*Q[x][a]+s.alpha*(reward+s.gamma*Math.max(...Q[y]));x=y;});return {charts:[heat('Learned Q-values (rows: rooms; columns: L,R,U,D)',Q)],tables:[table('Learned action values',['Room',...VAC.actions,'Greedy action'],Q.map((q,i)=>[VAC.rooms[i],...q,VAC.actions[q.indexOf(Math.max(...q))]])),table('Learned transitions from Living Room',['Action',...VAC.rooms,'Samples'],counts[0].map((row,a)=>[VAC.actions[a],...row.map(n=>L.sum(row)?n/L.sum(row):'unseen'),L.sum(row)]))],text:'Unseen state-action pairs are marked explicitly rather than divided by zero. This uses the notebook’s model-based counts and model-free Q update on the same experience.'};},[36,38,40,44,50]);
}
